apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  type: LoadBalancer
  selector:
    uuid: example-1234
  ports:
  - name: app
    port: 80
    targetPort: 4000
    protocol: TCP
  - name: mysql
    port: 3306
    targetPort: 3306
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
spec:
  selector:
    matchLabels:
      uuid: example-1234
  replicas: 1
  template:
    metadata:
      labels:
        uuid: example-1234
        env: development
    spec:
      containers:
      - name: app
        image: gcr.io/example-dev-a7b3bcf6/sampleapp:v1
        ports:
        - containerPort: 4000
        env:
        - name: PORT
          value: "4000"
        - name: LOG_LEVEL
          value: "info"
        - name: NODE_ENV
          value: "development"
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
